name: python ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 15 * * 0"

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # for EnricoMi/publish-unit-test-result-action
      checks: write
      pull-requests: write # for comment_mode
      contents: read # only for private repository
      issues: read # only for private repository
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - uses: actions/cache@v2
        id: poetry_cache_id
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: install dependencies
        if: steps.poetry_cache_id.outputs.cache-hit != 'true'
        shell: bash
        run: poetry install
      - name: lint with flake8
        continue-on-error: true
        run: |
          poetry run flake8 src/ tests/ --format junit-xml --output-file report.xml
          poetry run flake8 src/ tests/ --format html --htmldir=flake8
      - name: publish flake8 results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: flake8 results
          files: report.xml
      - name: upload flake8 report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: flake8-report
          path: flake8/
      - name: test with pytest
        continue-on-error: true
        run: |
          poetry run pytest
      - name: publish pytest results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: pytest results
          files: report.xml
      - name: upload pytest report
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pytest-report
          path: htmlcov/

  dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: build container
        id: build
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.IMAGE_NAME }}:alpha
          context: .
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar
          retention-days: 1

  trivy:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: load image
        run: docker load --input /tmp/myimage.tar

      - name: scan by trivy
        uses: aquasecurity/trivy-action@0.2.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:alpha"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: upload trivy scan results to gitHub security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"

  anchore-image:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: load image
        run: docker load --input /tmp/myimage.tar

      - name: scan image by anchore
        id: anchore-image
        uses: anchore/scan-action@v3
        with:
          image: "${{ env.IMAGE_NAME }}:alpha"
          severity-cutoff: low
          fail-build: false
          acs-report-enable: true

      - name: upload anchore scan results to gitHub security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.anchore-image.outputs.sarif }}

  anchore-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: scan files by anchore
        id: anchore-files
        uses: anchore/scan-action@v3
        with:
          path: "."
          severity-cutoff: low
          fail-build: false
          acs-report-enable: true

      - name: upload anchore scan results to gitHub security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.anchore-files.outputs.sarif }}

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: scan Dockerfile by hadolint
        uses: hadolint/hadolint-action@master
        with:
          recursive: true
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
